# Generated by Django 5.0.3 on 2026-07-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryperson",
            name="background_check_status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "No enviado"),
                    ("pending", "Pendiente"),
                    ("approved", "Aprobado"),
                    ("rejected", "Rechazado"),
                ],
                default="not_submitted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="deliveryperson",
            name="id_document_back",
            field=models.ImageField(blank=True, null=True, upload_to="kyc/delivery/"),
        ),
        migrations.AddField(
            model_name="deliveryperson",
            name="id_document_front",
            field=models.ImageField(blank=True, null=True, upload_to="kyc/delivery/"),
        ),
        migrations.AddField(
            model_name="deliveryperson",
            name="kyc_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryperson",
            name="kyc_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryperson",
            name="selfie",
            field=models.ImageField(blank=True, null=True, upload_to="kyc/delivery/"),
        ),
    ]
