# Generated by Django 5.0.3 on 2026-07-07 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customers.customeraddress'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
