# Generated by Django 5.0.3 on 2026-07-09 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_default_address_customer_phone_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="default_address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phone_verified",
        ),
    ]
