# Generated by Django 5.0.3 on 2025-08-06 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Auto'), ('motorcycle', 'Moto'), ('van', 'Camioneta')], max_length=20)),
                ('vehicle_brand', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_year', models.PositiveIntegerField()),
                ('vehicle_plate', models.CharField(max_length=20, unique=True)),
                ('vehicle_color', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('suspended', 'Suspendido'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('availability', models.CharField(choices=[('available', 'Disponible'), ('busy', 'Ocupado'), ('offline', 'Desconectado')], default='offline', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('accepted', 'Aceptado'), ('driver_arrived', 'Conductor llegó'), ('in_progress', 'En progreso'), ('completed', 'Completado'), ('cancelled_customer', 'Cancelado por cliente'), ('cancelled_driver', 'Cancelado por conductor')], default='requested', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('pickup_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('destination_address', models.TextField()),
                ('destination_latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('destination_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('estimated_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('actual_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('distance_fare', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('time_fare', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('customer_to_driver', 'Cliente a Conductor'), ('driver_to_customer', 'Conductor a Cliente')], max_length=20)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trip_ratings',
            },
        ),
    ]
