# Generated by Django 5.0.3 on 2026-07-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('requested', 'Solicitado'), ('accepted', 'Aceptado'), ('driver_arrived', 'Conductor llegó'), ('in_progress', 'En progreso'), ('completed', 'Completado'), ('cancelled_customer', 'Cancelado por cliente'), ('cancelled_driver', 'Cancelado por conductor'), ('cancelled_no_driver', 'Cancelado - sin conductor')], default='requested', max_length=20),
        ),
    ]
