# Generated by Django 5.0.3 on 2026-07-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobility", "0003_alter_trip_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="background_check_status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "No enviado"),
                    ("pending", "Pendiente"),
                    ("approved", "Aprobado"),
                    ("rejected", "Rechazado"),
                ],
                default="not_submitted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="id_document_back",
            field=models.ImageField(blank=True, null=True, upload_to="kyc/driver/"),
        ),
        migrations.AddField(
            model_name="driver",
            name="id_document_front",
            field=models.ImageField(blank=True, null=True, upload_to="kyc/driver/"),
        ),
        migrations.AddField(
            model_name="driver",
            name="kyc_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="kyc_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="selfie",
            field=models.ImageField(blank=True, null=True, upload_to="kyc/driver/"),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Solicitado"),
                    ("accepted", "Aceptado"),
                    ("driver_arrived", "Conductor llegó"),
                    ("in_progress", "En progreso"),
                    ("completed", "Completado"),
                    ("cancelled_customer", "Cancelado por cliente"),
                    ("cancelled_driver", "Cancelado por conductor"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
    ]
