# Generated by Django 5.0.3 on 2026-07-09 03:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_scheduled_time"),
        ("delivery", "0002_initial"),
        ("orders", "0002_initial"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="scheduled_time",
            field=models.DateTimeField(
                blank=True, help_text="Fecha/hora programada para el pedido", null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("scheduled", "Programado"),
                    ("confirmed", "Confirmado"),
                    ("preparing", "Preparando"),
                    ("ready", "Listo"),
                    ("on_route", "En camino"),
                    ("delivered", "Entregado"),
                    ("cancelled", "Cancelado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["scheduled_time"], name="orders_schedul_6c8791_idx"),
        ),
    ]
